# Generated by Django 2.1.7 on 2019-08-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodCVS',
            field=models.CharField(default='DEFAULT', max_length=40),
        ),
    ]
