# Generated by Django 2.1.7 on 2019-08-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_product_prodcvs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=255, unique=True)),
                ('prodType', models.CharField(max_length=20)),
                ('prodEventType', models.CharField(default='DEFAULT', max_length=20)),
                ('prodPrice', models.PositiveIntegerField()),
                ('prodImg', models.URLField(null=True)),
            ],
            options={
                'ordering': ['prodName'],
            },
        ),
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=255, unique=True)),
                ('prodType', models.CharField(max_length=20)),
                ('prodEventType', models.CharField(default='DEFAULT', max_length=20)),
                ('prodPrice', models.PositiveIntegerField()),
                ('prodImg', models.URLField(null=True)),
            ],
            options={
                'ordering': ['prodName'],
            },
        ),
        migrations.CreateModel(
            name='Product4',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=255, unique=True)),
                ('prodType', models.CharField(max_length=20)),
                ('prodEventType', models.CharField(default='DEFAULT', max_length=20)),
                ('prodPrice', models.PositiveIntegerField()),
                ('prodImg', models.URLField(null=True)),
            ],
            options={
                'ordering': ['prodName'],
            },
        ),
        migrations.CreateModel(
            name='Product5',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=255, unique=True)),
                ('prodType', models.CharField(max_length=20)),
                ('prodEventType', models.CharField(default='DEFAULT', max_length=20)),
                ('prodPrice', models.PositiveIntegerField()),
                ('prodImg', models.URLField(null=True)),
            ],
            options={
                'ordering': ['prodName'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodCVS',
        ),
        migrations.AlterField(
            model_name='product',
            name='prodEventType',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
