# Generated by Django 2.1.7 on 2019-08-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_product_prodcvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodEventType',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
